mutation CreateProcedure(
    $name: String!,
    $description: String,
    $price: Float!,
    $lab: Int!,
){
    upsertProcedure(input: {
        name: $name
        description: $description
        price: $price
        lab: $lab
    }){ 
        procedure {
            index
            name            
        }
        created
    }
}