stages:
    - build
    - test
    - deploy
  
image: docker:latest

services:
    - docker:dind
    
before_script:
- docker info
- apk update
- apk upgrade
- apk add python python-dev py-pip build-base
- pip install docker-compose
- docker run -d -p 5000:5000 --restart=always --name registry registry:2

build:
    stage: 'build'
    script:
        - docker-compose -f lab-manager/stack.yaml build
        - docker-compose -f lab-manager/stack.yaml push

test:
    stage: 'test'
    script:
        - docker-compose up -d
        - docker-compose exec api ./manage.py test
        - docker-compose exec client yarn test
        - docker-compose exec proxy nginx -t
        - docker-compose down

deploy:
    stage: 'deploy'
    script:
        - docker swarm init;
        - docker stack deploy --compose-file lab-manager/stack.yaml lab-manage