# Generated by Django 3.0.4 on 2020-03-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('process', 'index'), ('procedure', 'process')},
        ),
    ]
