# Generated by Django 3.0.4 on 2020-03-21 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200321_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-registration_date', 'patient'), 'verbose_name': 'Trabalho', 'verbose_name_plural': 'Trabalhos'},
        ),
        migrations.AlterField(
            model_name='job',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kind', to='jobs.Process', verbose_name='Tipo'),
        ),
    ]
