# Generated by Django 3.0.4 on 2020-04-23 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200321_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basejob',
            name='name',
        ),
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Trabalho'),
            preserve_default=False,
        ),
    ]
