# Generated by Django 3.0.6 on 2020-05-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200423_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='amoutn',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
