# Generated by Django 3.0.6 on 2020-05-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_amoutn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='amoutn',
            new_name='amount',
        ),
    ]
