# Generated by Django 3.0.6 on 2020-05-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200521_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retorno'),
        ),
    ]
