# Generated by Django 3.0.6 on 2020-05-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20200521_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
