# Generated by Django 3.0.7 on 2020-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20200521_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='need_color',
            field=models.BooleanField(blank=True, null=True, verbose_name='Precisa da cor do dente'),
        ),
    ]
