# Generated by Django 3.0.7 on 2020-06-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_auto_20200521_2214'),
        ('jobs', '0013_auto_20200611_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='labs.Laboratory'),
        ),
        migrations.AlterField(
            model_name='process',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='labs.Laboratory'),
        ),
    ]
