# Generated by Django 3.0.7 on 2020-06-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20200611_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='need_color',
            field=models.BooleanField(blank=True, null=True, verbose_name='Precisa da cor do dente'),
        ),
    ]
