# Generated by Django 3.0.7 on 2020-07-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_procedure_need_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
    ]
