# Generated by Django 3.0.3 on 2020-03-07 20:52

import crm.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labs', '0006_auto_20200224_0408'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFunnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrição')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='Indexação')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
            ],
            options={
                'verbose_name': 'Estágio',
                'verbose_name_plural': 'Estágios',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Funnel',
            fields=[
                ('basefunnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.BaseFunnel')),
                ('index', models.IntegerField(blank=True, editable=False, verbose_name='índice')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funnels', to='labs.Laboratory')),
            ],
            options={
                'verbose_name': 'Funil',
                'verbose_name_plural': 'Funis',
                'ordering': ['index'],
                'unique_together': {('index', 'lab')},
            },
            bases=('crm.basefunnel',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('address', models.TextField(max_length=200, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('index', models.IntegerField(blank=True, editable=False, verbose_name='índice')),
                ('discount', models.FloatField(default=0, validators=[crm.models.validate_discount], verbose_name='Desconto')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='labs.Laboratory')),
                ('stage_funnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.Stage')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['index'],
                'unique_together': {('index', 'lab')},
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Telefone ou celular')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('index', models.IntegerField(blank=True, editable=False, verbose_name='Índice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='crm.Client')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
                'ordering': ['index'],
                'unique_together': {('telephone', 'client')},
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('basefunnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.BaseFunnel')),
                ('index', models.IntegerField(blank=True, editable=False, verbose_name='índice')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='labs.Laboratory')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['index'],
                'unique_together': {('index', 'lab')},
            },
            bases=('crm.basefunnel',),
        ),
        migrations.AddField(
            model_name='stage',
            name='funnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.Funnel'),
        ),
        migrations.AddField(
            model_name='stage',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.State'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('registration_date', models.DateField(auto_now=True, verbose_name='Data de cadastro')),
                ('index', models.IntegerField(blank=True, editable=False, verbose_name='Índice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='crm.Client')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['name'],
                'unique_together': {('index', 'client')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('funnel', 'index')},
        ),
    ]
