# Generated by Django 3.0.4 on 2020-03-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together={('telephone', 'client', 'index')},
        ),
    ]
