# Generated by Django 3.0.4 on 2020-03-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20200312_0427'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together={('client', 'index')},
        ),
    ]
