# Generated by Django 3.0.4 on 2020-03-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200312_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='Telefone ou celular'),
        ),
    ]
