# Generated by Django 3.0.4 on 2020-04-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200322_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='index',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='índice'),
        ),
    ]
