# Generated by Django 3.0.4 on 2020-04-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200422_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='index',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Índice'),
        ),
    ]
