FROM node:lts-alpine

RUN mkdir /app
# faz da pasta 'app' o diretório atual de trabalho
WORKDIR /app

RUN npm install -g @vue/cli @vue/cli-service

# copia arquivos e pastas para o diretório atual de trabalho (pasta 'app')
COPY ./web .
