# Generated by Django 3.0.6 on 2020-05-22 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0012_auto_20200521_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do recebimento')),
                ('value', models.IntegerField(verbose_name='Valor recebido')),
                ('index', models.IntegerField(blank=True, verbose_name='Índice')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faturamento',
                'verbose_name_plural': 'Faturamento',
            },
        ),
    ]
