mutation CreateJob(
    $name: String!
    $description: String
    $price: Float
    $kind: Int!
    $patient: Int!
    $client: Int!
    $lab: Int!
    $deadline: DateTime!
){
    uspsertJob(input: {
        name: $name
        description: $description
        price: $price
        kind: $kind
        patient: $patient
        client: $client
        lab: $lab
        deadline: $deadline
    }){
        job {
            id
            index
            name
        }
        created
    }
}