# Generated by Django 3.0.3 on 2020-02-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20200223_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Endereço de email'),
        ),
    ]
