mutation CreateProcess(
    $name: String!,
    $description: String,
    $price: Float!,
    $lab: Int!,
    $stages: [StageProcessInput]
){
    upsertProcess(input: {
        name: $name
        description: $description
        price: $price
        lab: $lab
        stages: $stages
    }){ 
        process {
            index
            name            
        }
        created
    }
}