version: "3.7"

services: 
    proxy:
        image: nginx
        volumes:
          - ./server/proxy/dev/nginx/:/etc/nginx/:wr
        #   - ./server/api/static/:/usr/share/nginx/html/api/static/:wr
        restart: always
        environment:
          - NGINX_HOST=172.25.10.30
          - NGINX_PORT=80
        ports:
          - 80:80
          - 443:443
        networks: 
          backend:
            ipv4_address: 172.25.10.30

    client:
        build: 
            context: ./client/web/
            dockerfile: Dockerfile.dev
        restart: always
        volumes: 
            - ./client/web:/app:wr
        command: npm run serve
        networks: 
            backend:
                ipv4_address: 172.35.10.30
        depends_on: 
            - api
        networks: 
            backend:
                ipv4_address: 172.35.10.30

    api:
        build:
            context: ./server/api
            dockerfile: Dockerfile.dev
        command: ./manage.py runserver 0.0.0.0:8000
        environment: 
            DB_PASSWORD: password
            DB_USER: protetics
            DB_NAME: database
            DB_HOST: 172.25.20.10
            DB_PORT: 5432
        volumes: 
            - ./server/api:/code:wr
        restart: always
        depends_on: 
            - db
        networks: 
            db:
                ipv4_address: 172.25.20.10
            backend:
                ipv4_address: 172.35.10.10

    db:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: protetics
            POSTGRES_DB: database
        networks: 
            db:
                ipv4_address: 172.25.20.10

networks:     
    backend:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.35.10.1/16
    db:
        driver: bridge
        ipam:
            config: 
                - subnet: 172.25.20.1/32