pipeline {
    agent any
    stages {
        stage('Set up registry') {
            steps {
                sh 'if [docker container ls -f name=registry]; \
                    then \
                        docker run -d \
                        -e REGISTRY_HTTP_ADDR=127.0.0.1:5000 \
                        -p 5000:5000 \
                        --restart=always \
                        --name registry \
                        registry:2; \
                    else \
                        docker exec registry -d \
                        -e REGISTRY_HTTP_ADDR=127.0.0.1:5000 \
                        -p 5000:5000 \
                        --restart=always; \
                    fi'
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose -f lab-manager/stack.yaml build; \
                docker-compose -f lab-manager/stack.yaml push'
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose up -d; \
                docker-compose exec api ./manage.py test; \
                docker-compose exec client yarn test; \
                docker-compose down'
            }
        }
        stage('Deploy') {
            steps {
                sh 'docker swarm init; \
                docker stack deploy --compose-file lab-manager/stack.yaml lab-manager'
            }
        }
    }
}