pipeline {
    agent any
    stages {
        stage('Set up registry') {
            steps {
                sh 'docker run -d \
                    -e REGISTRY_HTTP_ADDR=127.0.0.1:5000 \
                    -p 5000:5000 \
                    --restart=always \
                    --name registry \
                    registry:2'
            }
        }
        stage('Build') {
            steps {
                sh 'docker-compose -f stack.yaml build'
                sh 'docker-compose -f stack.yaml push'
            }
        }
        stage('Test') {
            steps {
                sh 'docker-compose up -d'
                sh 'docker-compose exec api ./manage.py test'
                sh 'docker-compose exec client yarn test'
                sh 'docker-compose down'
            }
        }
        stage('Deploy') {
            sh 'docker swarm init'
            sh 'docker stack deploy --compose-file stack.yaml lab-manager'
        }
    }
}