mutation Register(
    $fullName: String!,
    $username: String!,
    $email: String!,
    $password: String!,
    $laboratory: String!,
){
    register(input:{
        fullName: $fullName,
        username: $username,
        email: $email,
        password: $password,
        laboratory: $laboratory,
    }){
        professional{
            fullName
            username
            email
        }
    }
}